# Generated by Django 4.1.7 on 2023-05-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=22, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=22, verbose_name='Отчество')),
                ('citizenship', models.CharField(max_length=222, verbose_name='Гражданство')),
                ('pob', models.CharField(max_length=32, verbose_name='Место рождения')),
                ('dob', models.DateField(verbose_name='Дата рождения')),
                ('vidDocument', models.CharField(max_length=222, verbose_name='Документ')),
                ('seria', models.IntegerField(verbose_name='Серия')),
                ('nomer', models.IntegerField(verbose_name='Номер')),
                ('organ', models.CharField(max_length=32, verbose_name='Орган')),
                ('snils', models.IntegerField(verbose_name='Снилс')),
                ('phone', models.IntegerField(verbose_name='Номер')),
                ('email', models.EmailField(max_length=32, verbose_name='Емайл')),
                ('sogl', models.BooleanField(verbose_name=' - Я отношусь к льготной категории в соотвествии с пунктом 1 статьи 333.35 НК RФ')),
                ('sogl1', models.BooleanField(verbose_name=' - Даю согласие на представление персональных данных третьим лицам с целью отображения в выписке')),
                ('req', models.CharField(max_length=222, verbose_name='Услуга')),
                ('vidobject', models.CharField(max_length=222, verbose_name='Вид обьекта')),
                ('adres', models.CharField(max_length=52, verbose_name='Адрес')),
                ('cad_nomer', models.CharField(max_length=24, verbose_name='Кадастровый номер')),
                ('documents', models.ImageField(upload_to='', verbose_name='Документы')),
                ('prim', models.CharField(max_length=220, verbose_name='Примечание')),
                ('status', models.CharField(default='В ожидании', max_length=22, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
